#########################################################################
####                         公共基础配置                              ####
#########################################################################
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true

logging:
  config: classpath:log4j2-spring.xml

#########################################################################
####                     mybatis plus 配置                            ####
#########################################################################
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.geekerstar.*.module.*.domain.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    db-config:
      select-strategy: not_empty

# jasypt加密的密匙 -Djasypt.encryptor.password=Y6M9fAJQdU7jNp5MW
jasypt:
  encryptor:
    password: Y6M9fAJQdU7jNp5MW

